name: Epic
description: Request a new epic.
title: "[EPIC]: "
labels: ["epic", "enhancement"]
assignees:
  - AbhinRustagi
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a new epic!
  - type: textarea
    id: what-epic
    attributes:
      label: What epic would you like to see?
      description: Please describe the epic you would like to see added.
      placeholder: Tell us what you want!
      value: "A new epic!"
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
      description: How do you think we should implement this epic?
      placeholder: Tell us how you think we should do it!
      value: "Here's how I think we should do it!"
  - type: markdown
    attributes:
      value: |
        ## Additional Information
        Please provide any additional information that you think will help us understand your epic request.
  - type: checkboxes
    id: checklist
    attributes:
      label: Epic checklist
      description: I have completed the following tasks before submitting this epic request.
      options:
        - label: This epic has not been requested before.
          required: false
        - label: I have considered alternative solutions.
          required: false
        - label: I have described the epic in detail.
          required: true
  - type: textarea
    id: epic-requirements
    attributes:
      label: Epic requirements
      description: What are the requirements for this epic?
      placeholder: Tell us what you want!
      value: "Here are the requirements!"
    validations:
      required: true
  - type: textarea
    id: epic-tasks
    attributes:
      label: Epic tasks
      description: What are the tasks for this epic?
      placeholder: Tell us what you want!
      value: "Here are the tasks!"
    validations:
      required: true
