name: Feature
description: Request a new feature.
title: "[FEATURE]: "
labels: ["enhancement"]
assignees:
  - AbhinRustagi
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a new feature!
  - type: input
    id: epic-name
    attributes:
      label: Epic name
      description: What epic does this feature belong to?
      placeholder: Tell us what epic this feature belongs to!
      value: "A new epic!"
  - type: textarea
    id: what-feature
    attributes:
      label: What feature would you like to see?
      description: Please describe the feature you would like to see added.
      placeholder: Tell us what you want!
      value: "A new feature!"
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
      description: How do you think we should implement this feature?
      placeholder: Tell us how you think we should do it!
      value: "Here's how I think we should do it!"
  - type: markdown
    attributes:
      value: |
        ## Additional Information
        Please provide any additional information that you think will help us understand your feature request.
  - type: checkboxes
    id: checklist
    attributes:
      label: Feature checklist
      description: I have completed the following tasks before submitting this feature request.
      options:
        - label: This feature has not been requested before.
          required: false
        - label: I have considered alternative solutions.
          required: false
        - label: I have described the feature in detail.
          required: true